language: node_js

node_js:
  - "6"
env:
  global:
    - CIELO_MERCHANT_ID=00000000-0000-0000-0000-000000000000
    - CIELO_MERCHANT_KEY=0123456789012345678901234567890123456789
    - CIELO_API_URL=https://apisandbox.cieloecommerce.cielo.com.br/

install: npm i

script: npm test

after_success: bash <(curl -s https://codecov.io/bash)