language: node_js

node_js:
  - "6"
env:
  global:
    - CIELO_MERCHANT_ID=d17aac90-7c60-43d8-99ae-c3d78825116f
    - CIELO_MERCHANT_KEY=IFKCYKBHOPHYEZJQXCISBGUEBRDNAXBVUIPGKFXQ
    - CIELO_API_URL=https://apisandbox.cieloecommerce.cielo.com.br/

install: npm i

script: npm test

after_success: bash <(curl -s https://codecov.io/bash)